FROM shortgpt-service:latest

RUN apt-get update 
RUN apt-get install -y wget \
    gconf-service libasound2 libatk1.0-0 \
    libcairo2 libcups2 libfontconfig1 \
    libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 \
    libpango-1.0-0 libxss1 fonts-liberation \
    libappindicator1 libnss3 lsb-release xdg-utils \
    libx11-xcb1 libxtst6 libxrandr2 libgconf-2-4 libxi6 libglib2.0-0

# download and install chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
RUN rm google-chrome-stable_current_amd64.deb

COPY shortGPT /app/shortGPT
COPY shortService/share_handler.py /app/share_handler.py
COPY shortService/db_util.py /app/db_util.py
COPY cookies.txt /app/
COPY client_secret.json /app/
COPY service_account_shortgpt.json /app/
COPY .env /app/.env

WORKDIR /app

CMD ["python3", "share_handler.py"]
